'use client';

import { useState } from 'react';
import type { Service } from '@/lib/mock-data';
import Modal from '@/components/admin/Modal';
import styles from '@/app/admin/admin.module.css';

const serviceCategories = ['Hair', 'Skin', 'Makeup', 'Nail', 'Bridal', 'Spa'];

export default function AdminServicesClient({ services }: { services: Service[] }) {
  const [showModal, setShowModal] = useState(false);

  return (
    <div>
      <div className={styles.pageHeader} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <h2 className={styles.pageTitle}>Services</h2>
        <button className="btn btn-primary btn-sm" onClick={() => setShowModal(true)}>+ Add Service</button>
      </div>

      <div className="table-wrapper">
        <table className="data-table">
          <thead>
            <tr>
              <th>Service Name</th>
              <th>Category</th>
              <th>Price</th>
              <th>Duration</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {services.map((s) => (
              <tr key={s.id}>
                <td style={{ fontWeight: 500 }}>{s.name}</td>
                <td><span className="tag tag-active">{s.category}</span></td>
                <td>{s.price && s.price > 0 ? `₹${s.price.toLocaleString('en-IN')}` : '-'}</td>
                <td className="text-muted">{s.duration || '-'}</td>
                <td>
                  <div style={{ display: 'flex', gap: 6 }}>
                    <button className="btn btn-outline btn-sm">Edit</button>
                    <button className="btn btn-outline btn-sm">Delete</button>
                  </div>
                </td>
              </tr>
            ))}
            {services.length === 0 && (
              <tr>
                <td colSpan={5} style={{ textAlign: 'center', padding: '2rem' }}>No services found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {showModal && (
        <Modal title="Add Service" onClose={() => setShowModal(false)}>
          <div className="modal-body">
            <p className="text-muted" style={{ marginBottom: 16 }}>Note: For now, services are automatically generated by placing images into the corresponding category folder in public/images/services/.</p>
            <div className="form-group">
              <label className="form-label">Service Name</label>
              <input className="form-input" placeholder="e.g. HD Makeup" disabled />
            </div>
          </div>
          <div className="modal-footer">
            <button className="btn btn-outline btn-sm" onClick={() => setShowModal(false)}>Close</button>
          </div>
        </Modal>
      )}
    </div>
  );
}
